[functions]
  directory = "netlify/functions"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/agents/:slug"
  to = "/.netlify/functions/:slug"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  
